<script setup lang="ts">
import { computed, ref } from "vue";

type AlertItem = { id: number; title: string; camera: string; location: string; time: string; level: "高" | "中" | "低"; type: string; status: "待处理" | "已确认" };
type RoleKey = "super_admin" | "security_lead" | "guard" | "counselor" | "supervisor" | "employee" | "auditor";
type Role = { key: RoleKey; name: string; desc: string; scope: string; permissions: string[] };

const roles: Role[] = [
  { key: "super_admin", name: "超级管理员", desc: "平台运维，拥有全部权限", scope: "园区全量", permissions: ["user:view", "role:view", "behavior:view", "trajectory:view", "report:view", "audit:view", "consent:view"] },
  { key: "security_lead", name: "园区安全负责人", desc: "安保/EHS 主管，负责异常行为与轨迹监测", scope: "园区全量", permissions: ["user:view", "role:view", "behavior:view", "trajectory:view", "report:view", "audit:view", "consent:view"] },
  { key: "guard", name: "安保/巡检人员", desc: "一线安保、巡检员，按辖区查看监测", scope: "指定区域/辖区", permissions: ["behavior:view", "trajectory:view", "report:view"] },
  { key: "counselor", name: "心理辅导员(EAP)", desc: "驻场咨询师、社工", scope: "仅本人", permissions: ["behavior:view", "report:view"] },
  { key: "supervisor", name: "部门主管", desc: "班组长、部门经理，仅看本部门脱敏数据", scope: "本部门（脱敏）", permissions: ["report:view"] },
  { key: "employee", name: "员工本人", desc: "被监测员工，查看本人授权与报表", scope: "仅本人", permissions: ["consent:view", "report:view"] },
  { key: "auditor", name: "合规审计员", desc: "审计/法务/HRBP，只读全量+导出审计", scope: "园区全量", permissions: ["user:view", "role:view", "behavior:view", "trajectory:view", "report:view", "audit:view", "consent:view"] },
];
const demoAccounts: Record<string, { name: string; username: string; password: string; dept: string }> = {
  super_admin: { name: "系统管理员", username: "admin", password: "admin123", dept: "IT运维部" }, security_lead: { name: "王安全", username: "security", password: "sec123", dept: "安保部" }, guard: { name: "李巡检", username: "guard", password: "guard123", dept: "安保部" }, counselor: { name: "张心理", username: "counselor", password: "coun123", dept: "EAP心理中心" }, supervisor: { name: "赵主管", username: "supervisor", password: "sup123", dept: "生产一部" }, employee: { name: "钱员工", username: "employee", password: "emp123", dept: "生产二部" }, auditor: { name: "孙审计", username: "auditor", password: "aud123", dept: "审计法务部" },
};
const isLoggedIn = ref(false);
const authMode = ref<"login" | "register">("login");
const loginRole = ref<RoleKey>("super_admin");
const currentRole = ref<Role>(roles[0]);
const currentUser = ref(demoAccounts.super_admin);
const loginForm = ref({ username: "admin", password: "admin123" });
const registerForm = ref({ name: "", username: "", password: "", role: "employee" as RoleKey });
const authError = ref("");
const activeNav = ref("总览");
const currentPath = ref(window.location.pathname === "/" ? "/dashboard" : window.location.pathname);
const selectedRange = ref("近 7 日");
const searchText = ref("");
const showNotice = ref(false);
const modalType = ref<"alert" | "device" | "log" | "track" | "workorder" | "none">("none");
const selectedItem = ref<Record<string, string>>({});
const operationLogs = ref([
  { id: "LOG-20250618-001", account: "admin", name: "系统管理员", module: "告警中心", action: "确认真实告警", time: "2025-06-18 10:42:23", result: "成功" },
  { id: "LOG-20250618-002", account: "security", name: "王安全", module: "轨迹管理", action: "导出轨迹报表", time: "2025-06-18 10:38:11", result: "成功" },
  { id: "LOG-20250618-003", account: "guard", name: "李巡检", module: "设备管理", action: "查看设备详情", time: "2025-06-18 10:25:44", result: "成功" },
]);
const alerts = ref<AlertItem[]>([
  { id: 1, title: "人员闯入禁行区域", camera: "CAM-023", location: "南门仓储区", time: "10:42:18", level: "高", type: "区域入侵", status: "待处理" },
  { id: 2, title: "人员徘徊异常", camera: "CAM-118", location: "研发楼一层大厅", time: "10:39:52", level: "中", type: "行为异常", status: "待处理" },
  { id: 3, title: "非机动车逆行", camera: "CAM-087", location: "园区东侧路口", time: "10:35:07", level: "中", type: "交通事件", status: "待处理" },
  { id: 4, title: "消防通道占用", camera: "CAM-041", location: "生产车间 B 区", time: "10:21:43", level: "低", type: "安全生产", status: "已确认" },
]);
const chartValues = [42, 58, 48, 76, 64, 91, 72, 84, 68, 96, 77, 88];
const navItems = computed(() => {
  const all = [{ name: "总览", icon: "⌂", path: "/dashboard", permission: "" }, { name: "实时轨迹", icon: "◉", path: "/track/realtime", permission: "behavior:view" }, { name: "历史轨迹", icon: "⌁", path: "/track/history", permission: "trajectory:view" }, { name: "设备管理", icon: "▣", path: "/device/list", permission: "behavior:view" }, { name: "数据管理", icon: "▤", path: "/data/index", permission: "report:view" }, { name: "告警待办", icon: "!", path: "/alarm/todo", badge: "12", permission: "behavior:view" }, { name: "权限管理", icon: "⚙", path: "/system/index", permission: "user:view" }, { name: "操作日志", icon: "≡", path: "/data/operation-log", permission: "audit:view" }];
  return all.filter((item) => !item.permission || currentRole.value.permissions.includes(item.permission));
});
const pageTitle = computed(() => ({ "/dashboard": "总览看板", "/track/realtime": "实时轨迹管理", "/track/history": "事后轨迹查询", "/device/list": "设备列表管理", "/data/index": "数据管理", "/data/abnormal-record": "异常行为记录", "/data/track-record": "轨迹记录", "/data/backup": "数据备份与恢复", "/data/user-profile": "用户资料管理", "/data/operation-log": "系统操作日志", "/alarm/todo": "告警待办队列", "/workorder/detail/WO-20250618-001": "处置工单详情", "/system/index": "权限管理", "/system/role": "角色管理", "/system/user": "账号管理", "/403": "无权限访问" }[currentPath.value] || "总览看板"));
const filteredAlerts = computed(() => {
  const keyword = searchText.value.trim().toLowerCase();
  if (!keyword) return alerts.value;
  return alerts.value.filter((item) => `${item.title}${item.camera}${item.location}${item.type}`.toLowerCase().includes(keyword));
});
const displayStats = computed(() => currentRole.value.key === "employee" ? [{ label: "我的授权状态", value: "正常" }, { label: "个人报表", value: "08" }, { label: "隐私保护", value: "开启" }, { label: "待确认事项", value: "01" }] : currentRole.value.key === "supervisor" ? [{ label: "本部门事件", value: "328" }, { label: "部门在线率", value: "99.2%" }, { label: "本月报表", value: "12" }, { label: "待关注事件", value: "06" }] : [{ label: "今日识别事件", value: "2,846" }, { label: "待处理预警", value: "12" }, { label: "活跃轨迹", value: "438" }, { label: "设备在线率", value: "98.6%" }]);

function navigate(path: string, label?: string) { currentPath.value = path; activeNav.value = label || (navItems.value.find((item) => item.path === path)?.name || pageTitle.value); window.history.pushState({}, "", path); }
function openModal(type: typeof modalType.value, item: Record<string, string> = {}) { modalType.value = type; selectedItem.value = item; }
function closeModal() { modalType.value = "none"; selectedItem.value = {}; }
function chooseRole(key: RoleKey) { loginRole.value = key; const account = demoAccounts[key]; loginForm.value = { username: account.username, password: account.password }; }
function login() { const account = demoAccounts[loginRole.value]; if (loginForm.value.username !== account.username || loginForm.value.password !== account.password) { authError.value = "用户名或密码错误，请使用演示账号登录"; return; } currentRole.value = roles.find((role) => role.key === loginRole.value) || roles[0]; currentUser.value = account; isLoggedIn.value = true; navigate("/dashboard", "总览"); authError.value = ""; }
function register() { if (!registerForm.value.name || !registerForm.value.username || !registerForm.value.password) { authError.value = "请完整填写注册信息"; return; } currentRole.value = roles.find((role) => role.key === registerForm.value.role) || roles[5]; currentUser.value = { name: registerForm.value.name, username: registerForm.value.username, password: registerForm.value.password, dept: "待完善部门" }; isLoggedIn.value = true; authMode.value = "login"; navigate("/dashboard", "总览"); authError.value = ""; }
function logout() { isLoggedIn.value = false; authMode.value = "login"; navigate("/login", "登录"); }
function markHandled(item: AlertItem) { item.status = "已确认"; showNotice.value = true; window.setTimeout(() => (showNotice.value = false), 2200); }
window.addEventListener("popstate", () => { currentPath.value = window.location.pathname; });
</script>

<template>
  <section v-if="!isLoggedIn" class="auth-page">
    <div class="auth-brand"><div class="auth-mark">观</div><div><strong>智行观测</strong><span>BEHAVIOR INSIGHT PLATFORM</span></div></div>
    <div class="auth-layout"><div class="auth-intro"><p class="eyebrow">SMART BEHAVIOR MANAGEMENT</p><h1>让园区安全<br /><span>看得见、管得住</span></h1><p>连接视频资源，洞察异常行为，构建更安全、更高效的园区运营体系。</p><div class="auth-features"><span>◉ 多源视频接入</span><span>⌁ 跨摄像头轨迹</span><span>◇ AI 异常识别</span></div></div>
      <div class="auth-card"><div class="auth-tabs"><button :class="{ active: authMode === 'login' }" @click="authMode = 'login'; authError = ''">登录系统</button><button :class="{ active: authMode === 'register' }" @click="authMode = 'register'; authError = ''">注册账号</button></div>
        <template v-if="authMode === 'login'"><h2>欢迎回来</h2><p class="auth-subtitle">登录您的园区行为管理工作台</p><label>登录角色</label><div class="role-selector"><button v-for="role in roles" :key="role.key" :class="{ selected: loginRole === role.key }" @click="chooseRole(role.key)">{{ role.name }}</button></div><label>用户名</label><div class="auth-input"><span>♙</span><input v-model="loginForm.username" placeholder="请输入用户名" /></div><label>密码</label><div class="auth-input"><span>◆</span><input v-model="loginForm.password" type="password" placeholder="请输入密码" @keyup.enter="login" /></div><p v-if="authError" class="auth-error">{{ authError }}</p><button class="auth-submit" @click="login">登录</button><div class="demo-hint">演示账号：选择角色后自动填充账号密码</div></template>
        <template v-else><h2>创建新账号</h2><p class="auth-subtitle">注册后将以指定角色进入系统</p><label>姓名</label><div class="auth-input"><span>♙</span><input v-model="registerForm.name" placeholder="请输入姓名" /></div><label>用户名</label><div class="auth-input"><span>@</span><input v-model="registerForm.username" placeholder="设置登录用户名" /></div><label>密码</label><div class="auth-input"><span>◆</span><input v-model="registerForm.password" type="password" placeholder="设置登录密码" /></div><label>注册角色</label><select v-model="registerForm.role" class="auth-select"><option v-for="role in roles.filter((item) => !['super_admin', 'security_lead', 'auditor'].includes(item.key))" :key="role.key" :value="role.key">{{ role.name }}</option></select><p v-if="authError" class="auth-error">{{ authError }}</p><button class="auth-submit" @click="register">注册并进入</button></template>
      </div></div>
  </section>
  <div v-else class="app-shell">
    <aside class="sidebar">
      <div class="brand">
        <div class="brand-mark">观</div>
        <div><strong>智行观测</strong><span>BEHAVIOR INSIGHT</span></div>
      </div>
      <div class="workspace-switcher"><span class="status-dot"></span><div><small>当前工作空间</small><b>城市治理示范区</b></div><span class="chevron">⌄</span></div>
      <nav class="nav-list">
        <p class="nav-label">工作台</p>
        <button v-for="item in navItems" :key="item.name" :class="['nav-item', { active: currentPath === item.path }]" @click="navigate(item.path, item.name)"><span class="nav-icon">{{ item.icon }}</span><span>{{ item.name }}</span><em v-if="item.badge">{{ item.badge }}</em></button>
        <template v-if="currentRole.permissions.includes('user:view') || currentRole.permissions.includes('role:view')"><p class="nav-label secondary">系统管理</p><button v-if="currentRole.permissions.includes('user:view')" class="nav-item" @click="navigate('/system/user', '账号管理')"><span class="nav-icon">♙</span><span>账号管理</span></button><button v-if="currentRole.permissions.includes('role:view')" class="nav-item" @click="navigate('/system/role', '角色管理')"><span class="nav-icon">⚙</span><span>角色管理</span></button></template>
      </nav>
      <div class="sidebar-bottom"><div class="help-card"><div class="help-icon">?</div><div><b>需要帮助？</b><span>查看操作手册</span></div><span class="arrow">→</span></div><div class="user-profile"><div class="avatar">{{ currentUser.name.slice(0, 1) }}</div><div><b>{{ currentUser.name }}</b><span>{{ currentRole.name }}</span></div><button class="logout-button" @click="logout">退出</button></div></div>
    </aside>

    <main class="main-content">
      <header class="topbar"><div><div class="breadcrumb">工作台 <span>/</span> <b>{{ activeNav }}</b></div><h1>{{ pageTitle }}</h1></div><div class="top-actions"><button class="date-select">◷ <span>2025年06月18日</span>⌄</button><button class="icon-button" @click="showNotice = true">♧<i></i></button><div class="top-avatar">{{ currentUser.name.slice(0, 1) }}</div></div></header>

      <section v-if="currentPath === '/dashboard'" class="content-area">
        <div class="welcome-row"><div><p class="eyebrow">WEDNESDAY, JUNE 18, 2025</p><h2>早上好，{{ currentUser.name }} <span>✦</span></h2><p class="muted">当前角色：{{ currentRole.name }}　·　数据范围：{{ currentRole.scope }}</p></div><button v-if="currentRole.permissions.includes('trajectory:view')" class="primary-button" @click="activeNav = '轨迹检索'">＋ 新建轨迹检索</button></div>

        <div class="metric-grid"><div v-for="(stat, index) in displayStats" :key="stat.label" class="metric-card"><div class="metric-top"><span :class="['metric-icon', ['blue', 'orange', 'violet', 'green'][index]]">{{ ['◎', '!', '⌁', '◉'][index] }}</span><span class="trend up">{{ index === 0 ? '↗ 今日' : '查看详情' }}</span></div><span class="metric-label">{{ stat.label }}</span><strong>{{ stat.value }}</strong><small>{{ currentRole.key === 'employee' ? '仅对本人可见' : currentRole.key === 'supervisor' ? '本部门数据' : '实时同步' }}</small></div></div>

        <div class="main-grid"><section class="panel trend-panel"><div class="panel-header"><div><h3>事件趋势</h3><p>多源视频分析事件实时统计</p></div><div class="range-tabs"><button v-for="range in ['今日','近 7 日','近 30 日']" :key="range" :class="{ chosen: selectedRange === range }" @click="selectedRange = range">{{ range }}</button></div></div><div class="chart-summary"><div><strong>18,429</strong><span>累计事件量</span></div><div class="chart-legend"><span><i class="dot blue-dot"></i>识别事件</span><span><i class="dot orange-dot"></i>有效预警</span></div></div><div class="chart"><div class="y-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div class="chart-body"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><div class="bars"><div v-for="(value, index) in chartValues" :key="index" class="bar-group"><div class="bar blue-bar" :style="{ height: `${value}%` }"><span class="tooltip" v-if="index === 9">{{ value + 124 }}</span></div><div class="bar orange-bar" :style="{ height: `${value * .58}%` }"></div><small>{{ ['00:00','02:00','04:00','06:00','08:00','10:00','12:00','14:00','16:00','18:00','20:00','22:00'][index] }}</small></div></div></div></div></section>

          <section class="panel status-panel"><div class="panel-header"><div><h3>运行状态</h3><p>今日 00:00 — 24:00</p></div><button class="more-button">•••</button></div><div class="donut-wrap"><div class="donut"><div><strong>98.6%</strong><span>设备在线</span></div></div></div><div class="status-list"><div><i class="status-green"></i><span>正常运行</span><b>1,248</b><em>98.6%</em></div><div><i class="status-yellow"></i><span>连接波动</span><b>14</b><em>1.1%</em></div><div><i class="status-red"></i><span>离线设备</span><b>4</b><em>0.3%</em></div></div><button class="text-button" @click="navigate('/device/list', '设备管理')">查看设备详情 <span>→</span></button></section></div>

        <div class="lower-grid"><section class="panel alert-panel"><div class="panel-header"><div><h3>实时预警 <span class="live-pill"><i></i> LIVE</span></h3><p>最近发生的异常行为事件</p></div><button class="text-button" @click="navigate('/alarm/todo', '告警待办')">查看全部 <span>→</span></button></div><div class="table-tools"><div class="search-box"><span>⌕</span><input v-model="searchText" placeholder="搜索事件、设备或位置" /></div><button class="filter-button">筛选 ⌄</button></div><div class="alert-table"><div class="table-head"><span>事件信息</span><span>位置 / 设备</span><span>发生时间</span><span>等级</span><span>状态</span><span></span></div><div v-for="item in filteredAlerts" :key="item.id" class="table-row"><div class="event-title"><span :class="['event-mark', item.level === '高' ? 'danger' : item.level === '中' ? 'warning' : 'normal']">{{ item.level === '高' ? '!' : '◆' }}</span><div><b>{{ item.title }}</b><small>{{ item.type }}</small></div></div><div><b>{{ item.location }}</b><small>{{ item.camera }}</small></div><span class="time">{{ item.time }}</span><span :class="['level-tag', item.level === '高' ? 'high' : item.level === '中' ? 'medium' : 'low']">{{ item.level }}风险</span><span :class="['status-tag', item.status === '已确认' ? 'done' : 'pending']">{{ item.status }}</span><button class="row-more" @click="markHandled(item)">{{ item.status === '待处理' ? '确认' : '•••' }}</button></div><div v-if="filteredAlerts.length === 0" class="empty-state">没有匹配的预警事件</div></div></section><section class="panel quick-panel"><div class="panel-header"><div><h3>快捷入口</h3><p>常用功能快速访问</p></div></div><div class="quick-list"><button @click="navigate('/track/history', '历史轨迹')"><span class="quick-icon blue">⌁</span><div><b>轨迹检索</b><small>跨镜头还原人员 / 车辆轨迹</small></div><span>→</span></button><button @click="navigate('/system/role', '角色管理')"><span class="quick-icon purple">◇</span><div><b>算法模型</b><small>管理 36 个行为识别模型</small></div><span>→</span></button><button @click="navigate('/device/list', '设备管理')"><span class="quick-icon green">▣</span><div><b>视频资源</b><small>1,266 路摄像头接入管理</small></div><span>→</span></button></div><div class="insight"><span>✦</span><div><b>智能洞察</b><p>今日 10:00—12:00 为事件高发时段，建议关注南门及生产车间区域。</p></div></div></section></div>
      </section>
      <section v-else class="content-area page-content">
        <div v-if="currentPath === '/403'" class="empty-page"><div class="empty-code">403</div><h2>暂无访问权限</h2><p>当前角色没有访问该页面的权限，请联系系统管理员。</p><button class="primary-button" @click="navigate('/dashboard', '总览')">返回总览</button></div>
        <template v-else-if="currentPath === '/data/index' || currentPath === '/system/index'"><div class="page-heading"><div><p class="eyebrow">MODULE NAVIGATION</p><h2>{{ pageTitle }}</h2><p class="muted">根据当前角色权限选择要进入的功能模块</p></div></div><div class="module-grid"><button v-if="currentPath === '/data/index'" class="module-card" @click="navigate('/data/abnormal-record', '异常行为记录')"><span>◉</span><b>异常行为记录</b><small>查询异常事件与分析报表</small></button><button v-if="currentPath === '/data/index'" class="module-card" @click="navigate('/data/track-record', '轨迹记录')"><span>⌁</span><b>轨迹记录</b><small>历史轨迹检索与轨迹回放</small></button><button v-if="currentPath === '/data/index'" class="module-card" @click="navigate('/data/backup', '数据备份')"><span>▣</span><b>数据备份与恢复</b><small>备份周期和历史版本管理</small></button><button v-if="currentPath === '/data/index'" class="module-card" @click="navigate('/data/user-profile', '用户资料')"><span>♙</span><b>用户资料管理</b><small>人员档案检索与资料维护</small></button><button v-if="currentPath === '/data/index' && currentRole.permissions.includes('audit:view')" class="module-card" @click="navigate('/data/operation-log', '操作日志')"><span>≡</span><b>系统操作日志</b><small>按账号、模块、时间查询审计记录</small></button><button v-if="currentPath === '/system/index' && currentRole.permissions.includes('role:view')" class="module-card" @click="navigate('/system/role', '角色管理')"><span>◇</span><b>角色管理</b><small>角色新增、编辑与权限模板配置</small></button><button v-if="currentPath === '/system/index' && currentRole.permissions.includes('user:view')" class="module-card" @click="navigate('/system/user', '账号管理')"><span>♙</span><b>账号管理</b><small>账号维护、角色分配和密码重置</small></button></div></template>
        <template v-else-if="currentPath === '/data/operation-log'"><div class="page-heading"><div><p class="eyebrow">AUDIT TRAIL</p><h2>系统操作日志</h2><p class="muted">日志仅支持查询、详情查看和导出，不允许修改或删除。</p></div><button class="primary-button" @click="showNotice = true">导出日志</button></div><div class="panel log-panel"><div class="table-tools"><div class="search-box"><span>⌕</span><input v-model="searchText" placeholder="按账号、模块或操作类型搜索" /></div><button class="filter-button">时间范围 ⌄</button></div><div class="log-row log-head"><span>日志编号</span><span>操作用户</span><span>模块 / 操作</span><span>时间</span><span>结果</span></div><button v-for="log in operationLogs.filter((item) => !searchText || `${item.account}${item.module}${item.action}`.includes(searchText))" :key="log.id" class="log-row" @click="openModal('log', log)"><span>{{ log.id }}</span><span><b>{{ log.name }}</b><small>{{ log.account }}</small></span><span><b>{{ log.module }}</b><small>{{ log.action }}</small></span><span>{{ log.time }}</span><span class="status-tag done">{{ log.result }}</span></button></div></template>
        <template v-else-if="currentPath === '/alarm/todo'"><div class="page-heading"><div><p class="eyebrow">ALERT WORKBENCH</p><h2>告警待办队列</h2><p class="muted">人工审核分级告警，确认真实告警后创建处置工单。</p></div></div><div class="panel queue-panel"><div v-for="item in alerts" :key="item.id" class="queue-row"><div class="event-title"><span :class="['event-mark', item.level === '高' ? 'danger' : 'warning']">!</span><div><b>{{ item.title }}</b><small>{{ item.location }} · {{ item.time }}</small></div></div><span :class="['level-tag', item.level === '高' ? 'high' : 'medium']">{{ item.level }}风险</span><button class="row-more" @click="openModal('alert', item)">核验详情</button></div></div></template>
        <template v-else-if="currentPath === '/workorder/detail/WO-20250618-001'"><div class="page-heading"><div><p class="eyebrow">WORK ORDER · WO-20250618-001</p><h2>处置工单详情</h2><p class="muted">完成现场派单、处置录入和工单归档。</p></div><button class="text-button" @click="navigate('/alarm/todo', '告警待办')">← 返回告警队列</button></div><div class="panel workorder-panel"><div class="workorder-status"><span class="status-tag pending">处理中</span><b>人员闯入禁行区域</b><small>南门仓储区 · CAM-023 · 10:42:18</small></div><div class="form-grid"><label>处置人员<input value="李巡检" /></label><label>处置时限<input value="2025-06-18 12:00" /></label><label class="full">处置记录<textarea placeholder="输入现场核验和处置结果"></textarea></label></div><button class="primary-button" @click="navigate('/alarm/todo', '告警待办')">完成处置并归档</button></div></template>
        <template v-else-if="currentPath === '/track/realtime' || currentPath === '/track/history'"><div class="page-heading"><div><p class="eyebrow">TRAJECTORY ANALYSIS</p><h2>{{ pageTitle }}</h2><p class="muted">{{ currentPath === '/track/realtime' ? '实时监控、目标追踪和实时告警展示。' : '历史轨迹检索、轨迹回放与报表导出。' }}</p></div><button class="primary-button" @click="openModal('track')">{{ currentPath === '/track/realtime' ? '开始目标追踪' : '检索轨迹' }}</button></div><div class="panel track-map"><div class="map-grid"><span v-for="n in 16" :key="n" :class="['map-point', { active: n % 5 === 0 }]" :style="{ left: `${(n * 29) % 92}%`, top: `${(n * 47) % 84}%` }">{{ n % 5 === 0 ? '●' : '' }}</span><div class="route-line"></div><b>园区视频轨迹空间</b></div><div class="track-results"><div><strong>438</strong><span>活跃目标</span></div><div><strong>24</strong><span>关联摄像头</span></div><div><strong>98.4%</strong><span>追踪连续率</span></div></div></div></template>
        <template v-else><div class="page-heading"><div><p class="eyebrow">{{ pageTitle.toUpperCase() }}</p><h2>{{ pageTitle }}</h2><p class="muted">当前页面为功能原型，支持查看、筛选和基础操作流程。</p></div><button class="primary-button" @click="showNotice = true">新增记录</button></div><div class="panel placeholder-panel"><div class="placeholder-icon">◇</div><h3>{{ pageTitle }}功能面板</h3><p>页面结构已按照清单预留，后续可接入真实接口和业务表单。</p><button class="text-button" @click="navigate('/dashboard', '总览')">返回总览 <span>→</span></button></div></template>
      </section>
    </main>
    <transition name="toast"><div v-if="showNotice" class="toast">✓ 操作已完成</div></transition>
    <div v-if="modalType !== 'none'" class="modal-backdrop" @click.self="closeModal"><div class="modal-card"><button class="modal-close" @click="closeModal">×</button><h3>{{ modalType === 'alert' ? '告警明细核验' : modalType === 'device' ? '设备详情' : modalType === 'log' ? '操作日志详情' : '轨迹检索' }}</h3><p v-if="modalType === 'alert'">{{ selectedItem.title || '实时异常行为事件' }}，支持调取主摄像头及周边摄像头进行二次核验。</p><p v-else-if="modalType === 'log'">操作用户：{{ selectedItem.name }}<br />模块：{{ selectedItem.module }}<br />动作：{{ selectedItem.action }}<br />时间：{{ selectedItem.time }}</p><p v-else>已打开功能操作面板，可继续完善筛选条件与业务数据。</p><div class="modal-actions"><button class="filter-button" @click="closeModal">取消</button><button class="primary-button" @click="modalType === 'alert' ? navigate('/workorder/detail/WO-20250618-001', '处置工单') : closeModal()">{{ modalType === 'alert' ? '判定真实告警并建单' : '确定' }}</button></div></div></div>
  </div>
</template>
